# Generated by Django 5.1 on 2024-08-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_material_umedida'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.categoriamaterial'),
        ),
    ]
