# Generated by Django 5.1.3 on 2024-11-26 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_categoriamaterial_alter_material_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Salida', 'Salida')], max_length=10)),
                ('rcantidad', models.IntegerField()),
                ('rrazon', models.CharField(choices=[('Compra', 'Compra'), ('Uso', 'Uso'), ('Traslado', 'Traslado')], max_length=20)),
                ('rfecha', models.DateTimeField(auto_now_add=True)),
                ('rproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.material')),
                ('rusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
