# Generated by Django 5.1.3 on 2024-11-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_registromaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rtipo',
            field=models.CharField(choices=[('Salida', 'Salida'), ('Ingreso', 'Ingreso')], max_length=10),
        ),
    ]
