# Generated by Django 5.1.3 on 2024-11-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_alter_registromaterial_rtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rrazon',
            field=models.CharField(choices=[('Traslado', 'Traslado'), ('Uso', 'Uso'), ('Compra', 'Compra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registromaterial',
            name='rtipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Salida', 'Salida')], max_length=10),
        ),
    ]
