# Generated by Django 5.1.3 on 2024-11-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_alter_registromaterial_rrazon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rrazon',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Uso', 'Uso'), ('Traslado', 'Traslado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registromaterial',
            name='rtipo',
            field=models.CharField(choices=[('Salida', 'Salida'), ('Ingreso', 'Ingreso')], max_length=10),
        ),
    ]
