# Generated by Django 5.1.3 on 2024-11-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_alter_registromaterial_rrazon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rrazon',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Traslado', 'Traslado'), ('Uso', 'Uso')], max_length=20),
        ),
    ]
