# Generated by Django 5.1.3 on 2024-11-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_alter_registromaterial_rrazon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rrazon',
            field=models.CharField(choices=[('Traslado', 'Traslado'), ('Uso', 'Uso'), ('Compra', 'Compra')], max_length=20),
        ),
    ]
