# Generated by Django 5.1.3 on 2024-11-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_alter_registromaterial_rrazon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rrazon',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Uso', 'Uso'), ('Traslado', 'Traslado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registromaterial',
            name='rtipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Salida', 'Salida')], max_length=10),
        ),
    ]
