# Generated by Django 5.1.7 on 2025-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0016_alter_registromaterial_rrazon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rrazon',
            field=models.CharField(choices=[('Traslado', 'Traslado'), ('Uso', 'Uso'), ('Compra', 'Compra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registromaterial',
            name='rtipo',
            field=models.CharField(choices=[('Salida', 'Salida'), ('Ingreso', 'Ingreso')], max_length=10),
        ),
    ]
