# Generated by Django 5.1.7 on 2025-04-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0017_alter_registromaterial_rrazon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rrazon',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Uso', 'Uso'), ('Traslado', 'Traslado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registromaterial',
            name='rtipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Salida', 'Salida')], max_length=10),
        ),
    ]
