# Generated by Django 5.1.7 on 2025-04-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0020_alter_registromaterial_rrazon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rrazon',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Traslado', 'Traslado'), ('Uso', 'Uso')], max_length=20),
        ),
    ]
