# Generated by Django 5.1.7 on 2025-05-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0021_alter_registromaterial_rrazon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rrazon',
            field=models.CharField(choices=[('Traslado', 'Traslado'), ('Uso', 'Uso'), ('Compra', 'Compra')], max_length=20),
        ),
    ]
