# Generated by Django 5.1.7 on 2025-05-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0022_alter_registromaterial_rrazon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rtipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Salida', 'Salida')], max_length=10),
        ),
    ]
