# Generated by Django 5.1.7 on 2025-05-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0023_alter_registromaterial_rtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromaterial',
            name='rrazon',
            field=models.CharField(choices=[('Uso', 'Uso'), ('Traslado', 'Traslado'), ('Compra', 'Compra')], max_length=20),
        ),
    ]
