# Generated by Django 5.1.7 on 2025-04-09 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('responsable', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('cxh', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('a_paterno', models.CharField(max_length=100)),
                ('a_materno', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('dni_img', models.ImageField(blank=True, null=True, upload_to='dni/')),
                ('f_nacimiento', models.DateField()),
                ('f_ingreso', models.DateField()),
                ('edad', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('cuenta_corriente', models.CharField(max_length=18)),
                ('cci', models.CharField(max_length=20)),
                ('t_zapato', models.CharField(max_length=2)),
                ('t_polo', models.CharField(max_length=2)),
                ('t_pantalon', models.CharField(max_length=2)),
                ('celular', models.CharField(max_length=9)),
                ('nro_emergencia', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=100)),
                ('e_civil', models.CharField(choices=[('Solter@', 'Solter@'), ('Casad@', 'Casad@'), ('Divorciad@', 'Divorciad@'), ('Viud@', 'Viud@')], max_length=20)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Despedido', 'Despedido')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retcc_img', models.ImageField(blank=True, null=True, upload_to='retcc/')),
                ('retcc_estado', models.CharField(choices=[('Vigente', 'Vigente'), ('Vencido', 'Vencido'), ('No tiene', 'No tiene')], max_length=20)),
                ('gremio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.gremio')),
                ('rango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.rango')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obrero_info', to='Personal.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Psindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_img_hijo', models.ImageField(blank=True, null=True, upload_to='SHdni/')),
                ('pcampo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sindicato_data', to='Personal.pcampo')),
            ],
        ),
        migrations.CreateModel(
            name='Psubcontrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcampo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subcontrato_data', to='Personal.pcampo')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200)),
                ('rm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_info', to='Personal.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Pcasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=10)),
                ('c_sol', models.CharField(max_length=30)),
                ('pcampo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='casa_data', to='Personal.pcampo')),
                ('srecomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.staff')),
            ],
        ),
    ]
