# Generated by Django 5.1.3 on 2024-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='f_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='f_nacimiento',
            field=models.DateField(),
        ),
    ]
