# Generated by Django 5.1.7 on 2025-04-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_alter_staff_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Personal',
        ),
    ]
