# Generated by Django 5.1.7 on 2025-04-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0003_rename_usuarios_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcampo',
            old_name='usuario',
            new_name='personal',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='usuario',
            new_name='personal',
        ),
    ]
