# Generated by Django 5.1.7 on 2025-04-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0004_rename_usuario_pcampo_personal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psindicato',
            name='pcampo',
        ),
        migrations.RemoveField(
            model_name='psubcontrato',
            name='pcampo',
        ),
        migrations.AddField(
            model_name='pcampo',
            name='c_sol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave SOL Obrero'),
        ),
        migrations.AddField(
            model_name='pcampo',
            name='ruc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RUC Obrero'),
        ),
        migrations.AddField(
            model_name='pcampo',
            name='sdni_img_hijo',
            field=models.ImageField(blank=True, null=True, upload_to='SHdni/', verbose_name='DNI del hijo'),
        ),
        migrations.AddField(
            model_name='pcampo',
            name='srecomendado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendados_staff', to='Personal.staff', verbose_name='Personal recomendado por Staff'),
        ),
        migrations.DeleteModel(
            name='Pcasa',
        ),
        migrations.DeleteModel(
            name='Psindicato',
        ),
        migrations.DeleteModel(
            name='Psubcontrato',
        ),
    ]
