# Generated by Django 5.1.7 on 2025-04-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0005_remove_psindicato_pcampo_remove_psubcontrato_pcampo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcampo',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC Obrero'),
        ),
    ]
