# Generated by Django 5.1.7 on 2025-04-30 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0006_alter_pcampo_ruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(db_index=True, unique=True, verbose_name='GeoName ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Distrito')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(db_index=True, unique=True, verbose_name='GeoName ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código ISO')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Pais')),
                ('divisa', models.CharField(max_length=3, verbose_name='Divisa del Pais')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(db_index=True, unique=True, verbose_name='GeoName ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='pcampo',
            name='retcc_estado',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Vencido', 'Vencido'), ('No tiene', 'No tiene')], default='No tiene', max_length=20),
        ),
        migrations.AlterField(
            model_name='personal',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nro_emergencia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='t_pantalon',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='personal',
            name='t_polo',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='personal',
            name='t_zapato',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='personal',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_distrito', to='Personal.distrito'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_pais', to='Personal.pais'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='Personal.provincia'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_provincia', to='Personal.provincia'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(db_index=True, unique=True, verbose_name='GeoName ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de ka Region/Departamento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='Personal.pais')),
            ],
            options={
                'verbose_name': 'Región/Departamento',
                'verbose_name_plural': 'Regiones/Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='Personal.region'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_region', to='Personal.region'),
        ),
    ]
