# Generated by Django 5.1.7 on 2025-05-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0007_distrito_pais_provincia_alter_pcampo_retcc_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='edad',
        ),
    ]
